name: Actualizar precios desde Excel

on:
  schedule:
    - cron: '0 22 * * *' # Todos los días a las 23:00 hora española (22:00 UTC)
  workflow_dispatch: # Permite ejecución manual

jobs:
  actualizar-precios:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script de actualización de precios
        run: node actualizarPrecios.js

      - name: Confirmar si hubo cambios
        run: |
          git config user.name "PedroGPT"
          git config user.email "actions@github.com"
          if git diff --quiet; then
            echo "Sin cambios, forzando commit vacío para redeploy"
            git commit --allow-empty -m "Forzar redeploy en Vercel"
          else
            echo "Hay cambios, haciendo commit normal"
            git add src/preciosReferencia.json
            git commit -m "Actualizar precios desde Excel"
          fi
          git push
